swagger: "2.0"
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: "1.0.0"
  termsOfService: "http://swagger.io/terms/"
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/login:
    post:
      tags:
        - User Module
      summary: Login
      description: API for Login
      parameters:
        - in: body
          name: body
          description: Login Payload
          required: true
          schema:
            $ref: "#/definitions/Login"
      produces:
        - application/json
      responses:
        "200":
          description: Login Successfully
          schema:
            $ref: "#/definitions/LoginResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
  /user/signup:
    post:
      tags:
        - User Module
      summary: Signup
      description: API for Signup
      parameters:
        - in: body
          name: body
          description: Signup Payload
          required: true
          schema:
            $ref: "#/definitions/User"
      produces:
        - application/json
      responses:
        "200":
          description: Signup Successfully
          schema:
            $ref: "#/definitions/ApiResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
  /user/profile:
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for fetching a user profile
      #produces:
      # - application/json
      responses:
        "200":
          description: User profile retrieved successully
          schema:
            $ref: "#/definitions/ApiResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for updating a user profile
      parameters:
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            $ref: "#/definitions/UserProfile"
      produces:
        - application/json
      responses:
        "200":
          description: User profile retrieved successully
          schema:
            $ref: "#/definitions/ApiResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
  # add routes phase 2
  /user/transactions:
    get:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: Current month user Transactions
      description: API for fetching transactions
      parameters:
        - in: body
          name: body
          description: current month & current year
          required: true
          schema:
            $ref: "#/definitions/Date"
      responses:
        "200":
          description: User transactions retrieved successully
          schema:
            $ref: "#/definitions/Transactions"
        "401":
          description: Unauthorized
        "500":
          description: Internal Server Error
  /user/transactions/{transactionId}:
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: post note user transaction
      description: API for post one user note
      parameters:
        - in: body
          name: body
          description: Update note
          required: true
          schema:
            $ref: "#/definitions/Transactionsnote"
      produces:
        - application/json
      responses:
        "201":
          description: Transaction note created successully
          schema:
            $ref: "#/definitions/Transactions"
        "400":
          description: Invalid Fields
        "401":
          description: Unauthorized
        "500":
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: Modify note user transaction
      description: API for updating a user note
      parameters:
        - in: body
          name: body
          description: Update user note
          required: true
          schema:
            $ref: "#/definitions/Transactionsnote"
      produces:
        - application/json
      responses:
        "200":
          description: User note update successully
          schema:
            $ref: "#/definitions/Transactions"
        "400":
          description: Invalid Fields
        "401":
          description: Unauthorized
        "500":
          description: Internal Server Error
    get:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: Get user transaction
      description: API for fetching one user transaction
      responses:
        "200":
          description: User transaction retrieved successfully
          schema:
            $ref: "#/definitions/Transactions"
        "401":
          description: Unauthorized
        "500":
          description: Internal Server Error
    delete:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: Delete user note
      description: API for deleting a user note
      responses:
        "200":
          description: User note deleted successfully
        "401":
          description: Unauthorized
        "500":
          description: Internal Server Error

securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  User:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
      firstName:
        type: string
        description: user first name
      lastName:
        type: string
        description: user last name
      userName:
        type: string
        description: user public name
  Login:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string
  LoginResponse:
    type: object
    properties:
      token:
        type: string
  UserProfile:
    type: object
    properties:
      userName:
        type: string
  # add definition phase 2
  Transactions:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          date:
            type: string
          description:
            type: string
          amount:
            type: string
          balance:
            type: string
          type:
            type: string
          category:
            type: string
          note:
            type: string
  Transactionsnote:
    properties:
      note:
        type: string
        description: user information
  Date:
    properties:
      date:
        type: string
        description: date
